#!/usr/bin/env python3
"""
adk_trace_inspector.py — Headless ADK 2.0 Event Trace Triage & Timing Tool
Parses NDJSON / JSONL event logs generated by `adk run --jsonl`,
extracts tool calls, verifies schema fidelity, analyzes timing/latency,
estimates token consumption, and flags execution errors.
"""

import sys
import json
import argparse
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass


def estimate_tokens(text: str) -> int:
    """Rough heuristic: ~4 characters per token."""
    return max(1, len(text) // 4)


def inspect_stream(stream, filter_tool: str = None, warn_duration: float = 5.0, as_json: bool = False) -> int:
    event_count = 0
    tool_calls = []
    errors = []
    routes = []
    total_tokens_estimated = 0
    slow_tools = []

    for line_num, line in enumerate(stream, start=1):
        line = line.strip()
        if not line:
            continue
        try:
            data = json.loads(line)
            event_count += 1
            total_tokens_estimated += estimate_tokens(line)

            event_type = data.get("event_type") or data.get("type", "unknown")

            # Tool call detection
            if "tool_call" in str(event_type).lower() or "tool" in data:
                name = data.get("name") or data.get("tool_name") or data.get("tool", "unnamed_tool")
                if filter_tool and filter_tool.lower() not in str(name).lower():
                    continue

                duration = data.get("duration") or data.get("duration_seconds") or 0.0
                if isinstance(duration, (int, float)) and duration >= warn_duration:
                    slow_tools.append({"name": name, "duration": duration, "line": line_num})

                tool_calls.append({
                    "line": line_num,
                    "name": name,
                    "args": data.get("args") or data.get("arguments", {}),
                    "duration": duration,
                })

            # Error detection
            if "error" in str(event_type).lower() or data.get("error") or data.get("status") == "error":
                errors.append({"line": line_num, "data": data})

            # Route detection
            if data.get("route"):
                routes.append(data.get("route"))

        except json.JSONDecodeError:
            continue

    summary = {
        "events_parsed": event_count,
        "tool_calls_count": len(tool_calls),
        "errors_count": len(errors),
        "branch_routes": routes or ["Linear"],
        "estimated_tokens": total_tokens_estimated,
        "slow_tools_count": len(slow_tools),
        "slow_tools": slow_tools,
        "tool_calls": tool_calls,
        "errors": errors,
    }

    if as_json:
        print(json.dumps(summary, indent=2))
        return 1 if errors else 0

    print("📊 ADK Trace Summary:")
    print(f"  • Total Events Parsed: {event_count}")
    print(f"  • Tool Calls Detected: {len(tool_calls)}")
    print(f"  • Estimated Tokens: ~{total_tokens_estimated:,}")
    print(f"  • Branch Routes Taken: {', '.join(str(r) for r in (routes or ['None (Linear)']))}")
    print(f"  • Errors Flagged: {len(errors)}")

    if slow_tools:
        print(f"\n⏱️ High-Latency Tool Calls (>= {warn_duration}s):")
        for st in slow_tools:
            print(f"  ⚠️ {st['name']} took {st['duration']}s (Line {st['line']})")

    if tool_calls:
        print(f"\n🔧 Tool Calls ({'Filtered' if filter_tool else 'All'}):")
        for idx, call in enumerate(tool_calls[:15], start=1):
            dur_str = f" [{call['duration']}s]" if call.get("duration") else ""
            print(f"  {idx}. {call['name']}{dur_str}({call['args']})")
        if len(tool_calls) > 15:
            print(f"  ... and {len(tool_calls) - 15} more tool calls")

    if errors:
        print("\n❌ Errors Encountered:")
        for idx, err in enumerate(errors, start=1):
            print(f"  {idx}. Line {err['line']}: {err['data']}")
        return 1

    print("\n✅ Trace Triaged Successfully — Zero Runtime Errors.")
    return 0


def main():
    parser = argparse.ArgumentParser(description="Headless ADK 2.0 Event Trace Triage & Timing Tool.")
    parser.add_argument("log_path", nargs="?", default="-", help="Path to NDJSON/JSONL log file (or '-' for stdin)")
    parser.add_argument("--json", action="store_true", help="Output summary in machine-parseable JSON")
    parser.add_argument("--filter-tool", help="Filter analysis by specific tool name")
    parser.add_argument("--slow-threshold", type=float, default=5.0, help="Flag tool calls exceeding this threshold (seconds, default: 5.0)")

    args = parser.parse_args()

    if args.log_path != "-":
        path = Path(args.log_path)
        if not path.exists():
            print(f"Error: Log file not found at '{path}'", file=sys.stderr)
            sys.exit(1)
        with open(path, "r", encoding="utf-8") as f:
            sys.exit(inspect_stream(f, filter_tool=args.filter_tool, warn_duration=args.slow_threshold, as_json=args.json))
    else:
        sys.exit(inspect_stream(sys.stdin, filter_tool=args.filter_tool, warn_duration=args.slow_threshold, as_json=args.json))


if __name__ == "__main__":
    main()
