#!/usr/bin/env python3
"""
adk_trace_inspector.py — Headless ADK 2.0 Event Trace Triage Tool
Parses NDJSON / JSONL event logs generated by `adk run --jsonl`,
extracts tool calls, verifies schema fidelity, and flags execution errors.
"""

import sys
import json
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass


def inspect_stream(stream):
    event_count = 0
    tool_calls = []
    errors = []
    routes = []

    for line_num, line in enumerate(stream, start=1):
        line = line.strip()
        if not line:
            continue
        try:
            data = json.loads(line)
            event_count += 1
            event_type = data.get("event_type") or data.get("type", "unknown")

            if "tool_call" in event_type or "tool" in data:
                tool_calls.append(data)
            if "error" in event_type or data.get("error") or data.get("status") == "error":
                errors.append(data)
            if data.get("route"):
                routes.append(data.get("route"))

        except json.JSONDecodeError:
            continue

    print(f"📊 ADK Trace Summary:")
    print(f"  • Total Events Parsed: {event_count}")
    print(f"  • Tool Calls Detected: {len(tool_calls)}")
    print(f"  • Branch Routes Taken: {routes or 'None (Linear)'}")
    print(f"  • Errors Flagged: {len(errors)}")

    if tool_calls:
        print("\n🔧 Tool Calls:")
        for idx, call in enumerate(tool_calls, start=1):
            name = call.get("name") or call.get("tool_name", "unnamed_tool")
            args = call.get("args") or call.get("arguments", {})
            print(f"  {idx}. {name}({args})")

    if errors:
        print("\n❌ Errors Encountered:")
        for idx, err in enumerate(errors, start=1):
            print(f"  {idx}. {err}")
        return 1

    print("\n✅ Trace Triaged Successfully — Zero Runtime Errors.")
    return 0

def main():
    if len(sys.argv) > 1 and sys.argv[1] != "-":
        log_path = Path(sys.argv[1])
        if not log_path.exists():
            print(f"Error: Log file not found at '{log_path}'")
            sys.exit(1)
        with open(log_path, "r", encoding="utf-8") as f:
            sys.exit(inspect_stream(f))
    else:
        # Read from stdin
        sys.exit(inspect_stream(sys.stdin))

if __name__ == "__main__":
    main()
